/*-------------------------------------------------------

// Tipos Primitivos

//Boolean
var TrueOrFalse = false;
console.log(typeof(TrueOrFalse));

//Number
var numero = 0;
console.log(typeof(numero));

//String 
var string = 'Derrubei café';
console.log(typeof(string)); */

/* -----------------------------------------------------

// Como declarar Variável

var variavel = 'Marvel';
variavel = 'Dc';
console.log(variavel);

let variavel2 = 'Marvete';
variavel2 = 'Dcnauta';
console.log(variavel2);

const variavel3 = 'Robson';
console.log(variavel3);

var EscopoGlobal = 'global';
console.log(EscopoGlobal);

function EscopoLocal (){
    let EscopoLocalInterno = 'local';
    console.log(EscopoLocalInterno);
}
EscopoLocal(); 

//Atribuição
var Atribuição = 'Gatos'; */

/* -----------------------------------------------------

// Operadores Aritméticos

//Comparação
var Comparação = '0' == 0; 
console.log();

//Comparação Identica
var ComparaçãoIdentica = '0' === 0;
console.log(ComparaçãoIdentica); 

//Adição
var adicao = 1 + 1;
console.log(adicao);

//Subtração
var subtracao = 2 - 1;
console.log(subtracao);

//Multiplicação
var multiplicacao = 2 * 3;
console.log(multiplicacao);

//Divisão Real
var DivisaoReal = 9 / 3;
console.log(DivisaoReal);

//Divisão Inteira
var DivisaoInteira = 2 % 4;
console.log(DivisaoInteira);

//Potenciação

var Potenciacao = 2 ** 8;
console.log(Potenciacao); */

/* ------------------------------------------------------------ 

// Operadores Relacionais

//Maior que
var MaiorQue = 5 > 2;
console.log(MaiorQue);

//Menor que
var MenorQue = 7 < 10;
console.log(MenorQue);

//Maior ou igual a
var MaiorOuIgual = 9 >= 8;
console.log(MaiorOuIgual);

//Menor ou igual a 
var MenorOuIgual = 2 <= 5;
console.log(MenorOuIgual); */

/* ---------------------------------------------------------------- 

// Operadores Lógicos

var e = true && false;
console.log(e);

var ou = true || false;
console.log(ou);

var nao = !true;
console.log(nao); */