/* ----------------------------------------------------------------------------------------------------------------

// Funções

function funcao() {
console.log('Robson')
}

funcao(); */

/* ----------------------------------------------------------------------------------------------------------------

//Função com Parãmetro

function mensagem(Renatinho, Marquinhos){
    console.log(Renatinho, Marquinhos)
}

mensagem('Ohana quer dizer família', 'Catchau'); */